florimondmanca/www

- package.json
- src/www/blog/site/.vuepress/config.js
- yarn.lock
GDPR disclaimer: [VuePress anonymizes IP by default](https://vuepress.vuejs.org/plugin/official/plugin-google-analytics.html#usage)
> Configure Google Analytics

- package.json
- src/www/blog/__init__.py
- src/www/blog/site/.vuepress/config.js
- src/www/web/app.py
- tests/test_blog.py
- yarn.lock
> Add sitemap

- package.json
- src/www/blog/app.py
- src/www/blog/middleware.py
- src/www/blog/settings.py
- src/www/blog/site/.vuepress/config.js
- src/www/blog/site/.vuepress/config.shared.json
- src/www/blog/site/.vuepress/plugin-blog/index.js
- tests/test_blog.py
- tests/utils.py
- yarn.lock
> Add RSS feed

- requirements-dev.txt
- setup.cfg
- tests/conftest.py
- www/app.py
Refs https://github.com/florimondmanca/asgi-lifespan/pull/30
> Upgrade asgi-lifespan

- .buildpacks
- .travis.yml
- README.md
- runtime.txt
> Upgrade to Python 3.8

- setup.cfg
- www/app.py
- www/middleware.py
- www/resources.py
- www/settings.py
Motivation: be able to know if legacy domains are still visited, and how much.
> Submit `requested_host` tag with traces

- requirements.txt
- setup.cfg
- www/app.py
- www/blog/routes.py
- www/middleware.py
- www/settings.py
Drops `ddtrace-asgi` in favor of manually submitting metrics and traces.
> Setup manual monitoring

- www/app.py
- www/blog/events.py
- www/resources.py
- www/settings.py
Aims at reducing the scope of #40.
> Refactor settings

- tests/test_monitoring.py
- tests/unit/test_utils.py
- www/app.py
- www/monitoring.py
- www/resources.py
- www/settings.py
- www/utils.py
> Add tests for monitoring

- www/app.py
- www/blog/__init__.py
- www/blog/content.py
**Motivation**
Reduce scope of #45
> Refactor blog startup hook

- ci/azure-pipelines.yml
- ci/templates/install.yml
**Motivation**
Reduce calls to PyPI.
> Cache Python dependencies on CI

- www/app.py
- www/blog/__init__.py
- www/blog/event_handlers.py
- www/monitoring.py
**Motivation**
Reduce scope of #51.
> Refactor event handlers

- www/sass/_util.scss
- www/sass/components/_jumbotron.scss
- www/sass/components/pages/_article_meta.scss
- www/sass/components/pages/_article_page.scss
- www/sass/components/pages/_index.scss
- www/sass/components/pages/_page_list_item.scss
- www/sass/components/pages/_tag_list.scss
- www/sass/mixins/_util.scss
- www/static/css/styles.css
- www/templates/components/jumbotron.jinja
- www/templates/components/pages/article_meta.jinja
- www/templates/components/pages/article_page.jinja
- www/templates/components/pages/page_list_item.jinja
- www/templates/components/pages/tag_list.jinja
- www/templates/views/home.jinja
> Responsiveness fixes

- content/articles/2018/09/consuming-apis-in-angular-the-model-adapter-pattern.md
- content/articles/2019/03/real-time-chatbot-server-python-bocadillo.md
- content/articles/2019/07/introducing-tartiflette-starlette.md
- content/articles/2019/08/introduction-to-asgi-async-python-web.md
- content/articles/2019/11/starlette-migrate-blog-across-domains.md
Make sure articles use absolute links to currently valid URLs, instead of redirected legacy ones.
> Fix legacy URL references

- content/articles/2019/08/introduction-to-asgi-async-python-web.md
Asynchronous Standard Gateway Interface > Asynchronous Server Gateway Interface
> Fixing ASGI acronym

- gulpfile.js
- server/static/css/styles.css
- server/styles/base.pcss
- server/styles/dracula.css
> Switch to Dracula for code blocks theming

- requirements.in
- requirements.txt
- scripts/check
- scripts/lint
- setup.cfg
See https://timothycrosley.github.io/isort/CHANGELOG/#500-penny-july-4-2020
> Use isort 5

- requirements.in
- requirements.txt
- server/reload.py
Refs https://github.com/florimondmanca/arel/pull/16
> Use arel 0.2.0, reload on templates and static files changes

- server/tools/mdformat.py
- tests/test_mdformat.py
> mdformat: Fix and test newline handling

- server/templates/components/comments.jinja
- server/templates/components/pages/article_page.jinja
> Add Comments sections via utterances

- ci/azure-pipelines.yml
References:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops
- http://dokku.viewdocs.io/dokku/deployment/user-management/#adding-ssh-keys
> Deploy on master builds

- content/articles/2019/02/consuming-apis-in-angular-displaying-data-in-components.md
- content/articles/2019/11/starlette-migrate-blog-across-domains.md
- requirements.txt
- server/content.py
- server/legacy.py
- server/tools/mdformat.py
- tests/test_legacy_redirect.py
Committed via https://github.com/asottile/all-repos
> Use and pin Black 20

- server/styles/components.pcss
- server/templates/components/pages/article_meta.jinja
- server/templates/components/pages/page_list.jinja
- server/templates/components/pages/page_list_item.jinja
- server/templates/components/pages/tag_list.jinja
- server/templates/components/pages/tag_page.jinja
- server/templates/views/home.jinja
- server/templates/views/page.jinja
- tailwind.config.js
Here's what this now looks like…
> Use grid layout for lists of articles

- server/resources.py
- server/templates/components/pages/article_meta.jinja
- tests/test_templates.py
> Use human-friendly date format

- tailwind.config.js
Prompted by https://github.com/florimondmanca/www/pull/151#issuecomment-747686087
> System fonts, continued

- server/reload.py
> Include extra content dirs in hot reload

- content/articles/2018/07/a-practical-usage-of-chainmap-in-python.md
- content/articles/2018/07/cheap-and-easy-deployment-captainduckduck-1.md
- content/articles/2018/07/let-the-journey-begin.md
- content/articles/2018/07/why-i-started-using-python-type-annotations-and-why-you-should-too.md
- content/articles/2018/08/cheap-and-easy-deployment-captainduckduck-2.md
- content/articles/2018/08/python-mutable-defaults-are-the-source-of-all-evil.md
- content/articles/2018/08/restful-api-design-13-best-practices-to-make-your-users-happy.md
- content/articles/2018/09/breaking-news-everything-is-an-event.md
- content/articles/2018/09/building-a-streaming-fraud-detection-system-with-kafka-and-python.md
- content/articles/2018/09/consuming-apis-in-angular-the-model-adapter-pattern.md
- content/articles/2018/10/from-angular-to-vue-feeling-like-a-beginner-again.md
- content/articles/2018/10/inbox-zero-how-to-keep-clean-email-inbox-and-mind.md
- content/articles/2018/10/reconciling-dataclasses-and-properties-in-python.md
- content/articles/2018/10/streaming-applications-with-apache-kafka-the-opening.md
- content/articles/2018/12/how-i-built-a-web-framework-and-became-an-open-source-maintainer.md
- content/articles/2019/02/consuming-apis-in-angular-displaying-data-in-components.md
- content/articles/2019/03/real-time-chatbot-server-python-bocadillo.md
- content/articles/2019/05/attending-tech-conferences-beginner-guide.md
- content/articles/2019/05/why-i-dont-write-on-medium.md
- content/articles/2019/06/vuepress-upgrade-1-0.md
- content/articles/2019/07/introducing-tartiflette-starlette.md
- content/articles/2019/08/introduction-to-asgi-async-python-web.md
- content/articles/2019/09/python-optionally-parametrized-decorators.md
- content/articles/2019/11/starlette-migrate-blog-across-domains.md
- content/articles/2020/05/structuring-starlette-projects.md
- content/articles/2020/07/utterances-comments-personal-sites-github.md
- content/articles/2021/04/google-floc.md
- tests/drafts/articles/2020/01/test-draft.md
- tests/test_content.py
Not used anymore in code. Drafts are managed differently now, see #157.
> Drop unused 'published' frontmatter attr

- tests/test_legacy_redirect.py
Readability and added "expect 404" case.
> Improve legacy redirect test

- server/content.py
- server/models.py
- server/templates/views/home.jinja
- server/templates/views/page.jinja
- server/views.py
> Remove remaining references to "articles"

- locale/base.pot
- locale/fr_FR/LC_MESSAGES/messages.po
- server/i18n/gettext.py
- server/i18n/jinja2.py
- server/templates/components/footer.jinja
- server/templates/components/jumbotron.jinja
- server/templates/components/pages/post_list.jinja
- server/templates/components/social_links.jinja
Add remaining FR translations for the website skeleton.
> Add remaining skeleton FR translations

- server/i18n/routing.py
- server/resources.py
- server/settings.py
- server/templates/components/navbar.jinja
- tests/test_i18n.py
Follow-up to #231: add EN / FR language switch.
> Add language switch

- content/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil.md
- requirements-dev.txt
- server/tools/mdformat.py
> Switch to pytest-codeblocks for mdformat extraction

- requirements.txt
- server/application/markdown.py
- server/content.py
- server/di.py
- server/domain/repositories.py
- server/infrastructure/adapters/markdown.py
- server/infrastructure/repositories.py
- server/main.py
- server/resources.py
- server/web/sitemap.py
- server/web/views.py
- tests/test_app.py
- tests/test_content.py
- tests/test_images.py
- tests/test_markdown.py
Follow-up to #332 
App is now programmed against the `PageRepository` interface. The specific in-memory implementation is mostly treated as an implementation detail. DI is managed using `punq`.
Also extract Markdown renderer, which makes `server/resources.py` disappear.
> Separate page repository interface from implementation

- server/domain/entities.py
- server/domain/repositories.py
- server/infrastructure/pages.py
- server/infrastructure/repositories.py
- server/web/templates/components/pages/tag_list.jinja
- server/web/templates/views/page.jinja
- tests/test_content.py
Follow-up to #334
Target domain structure:
* `Content`
* `Page`
* `Article`
* `Tag`
* `Category`
> Add Tag entity

- server/application/handlers.py
- server/application/parsers.py
- server/application/queries.py
- server/application/sources.py
- server/di.py
- server/infrastructure/database.py
- server/infrastructure/module.py
- server/infrastructure/parsers.py
- server/infrastructure/sources.py
- server/seedwork/domain/cqrs.py
- server/seedwork/infrastructure/cqrs.py
- server/tools/mdformat.py
- server/web/templating.py
- tests/test_content.py
> Extract GetPages query

- babel.cfg
- locale/base.pot
- locale/fr_FR/LC_MESSAGES/messages.po
- server/application/handlers.py
- server/di.py
- server/domain/entities.py
- server/domain/repositories.py
- server/infrastructure/parsers.py
- server/infrastructure/repositories.py
- server/web/templates/components/navbar.jinja
- server/web/templates/components/pages/category_page.jinja
- server/web/templates/components/pages/post_meta.jinja
- server/web/templating.py
- tests/test_app.py
- tests/test_content.py
- tests/test_templates.py
> Extract CategoryRepository

- .buildpacks
- ci/azure-pipelines.yml
- package.json
Node 18.x is the new LTS. https://nodejs.org
> Use Node 18

- package-lock.json
> Bump JS deps

- tailwind.config.js
> Use Georgia font everywhere

- Makefile
- ci/azure-pipelines.yml
- requirements.txt
- server/main.py
- setup.cfg
- tests/e2e/conftest.py
- tests/e2e/test_e2e.py
- tests/e2e/util.py
> Add initial E2E tests

- server/web/styles/defaults.css
- server/web/styles/diypedals/defaults.css
- server/web/styles/diypedals/index.css
- server/web/styles/diypedals/reset.css
- server/web/styles/diypedals/variables.css
- server/web/styles/layouts/container.css
- server/web/styles/variables.css
- server/web/templates/components/jumbotron.jinja
- server/web/templates/components/navbar.jinja
- server/web/templates/sites/diypedals/base.jinja
- server/web/templates/sites/diypedals/index.jinja
- server/web/templates/views/post/detail.jinja
* Font size was 20% too big.
* Margins, paddings, and other spacings based on `var(--v)` and `var(--w)` were using `rem` which meant bigger margins etc if users try to increase the font size, which is incorrect. Use `px` instead.
> Fix spacing

- ansible/environments/prod/group_vars/web.yml
- ansible/roles/www/defaults/main.yml
- ansible/roles/www/templates/.env.j2
- server/settings.py
- server/web/templates/base.jinja
* Refs #160 
This PR adds the `<link rel="webmention">` on pages, as per instructions from https://webmention.io/settings
> Add webmentions.io url

- server/web/templates/base.jinja
- server/web/templates/components/footer.jinja
- tests/conftest.py
- tests/test_indieweb.py
- tests/utils.py
* Refs #160 
Add `rel="me"` to social links that belong to me, as per step 2 of Level 1 of https://indiewebify.me/
> Add rel="me" to social links

- server/infrastructure/html.py
- server/infrastructure/urls.py
- server/web/sitemap.py
- server/web/templates/base.jinja
- server/web/templates/components/jumbotron.jinja
- server/web/templates/components/keyword_list.jinja
- server/web/templates/components/post_meta.jinja
- server/web/templates/views/post/detail.jinja
- server/web/templating.py
- tests/infrastructure/test_urls.py
- tests/test_app.py
- tests/test_content.py
- tests/test_indieweb.py
- tests/test_legacy_redirect.py
- tests/utils.py
* Refs #160 
Follow-up to #482 based on validation feedback from:
* https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fflorimond.dev
* https://indiewebify.me/validate-h-entry/?url=https%3A%2F%2Fflorimond.dev%2Fen%2Fposts%2F2022%2F07%2Fgithub-signed-commits
> Microformats, continued

- README.md
- ansible/roles/pyenv/defaults/main.yml
- ci/azure-pipelines.yml
- requirements.txt
Possible now that https://github.com/florimondmanca/arel/pull/34 has been released
> Use Python 3.12
