src/blog/routes.py
tests/test_blog.py
tests/test_legacy_redirect.py

Proper fix as a follow-up for https://github.com/florimondmanca/www/commit/e288b2277fd82869db330f3d9d455f23ab85a8cf. Rely on Starlette's automatic trailing slash handling and prefer URLs that end with `/`.

Prefer trailing slashes in URLs

---

www/sass/_code.scss
www/sass/_components.scss
www/sass/_util.scss
www/sass/app/_index.scss
www/sass/app/components/_index.scss
www/sass/app/components/_list_item.scss
www/sass/app/components/_navbar.scss
www/sass/app/layouts/_article_detail.scss
www/sass/app/layouts/_index.scss
www/sass/app/layouts/_layout.scss
www/sass/mixins/_index.scss
www/sass/mixins/_responsive.scss
www/sass/mixins/_util.scss
www/sass/styles.scss
www/sass/variables/_index.scss
www/static/css/styles.css

`styles.css` contained many duplicated rules. This PR switches to [`@use`](https://sass-lang.com/documentation/at-rules/use) instead of `@import`.

Optimize Sass imports

---

content/articles/2018/10/reconciling-dataclasses-and-properties-in-python.md

The last example should actually use `dataclasses.field()` in the assignment, instead of the type annotation. Other examples in the article do the correct thing, so I assume this was an oversight. Although it's pretty obvious how `field()` should be used, fixing it would be great.
Also, 👏 for this great article and the effort behind it.

Fix incorrect code in last example

---

content/articles/2019/02/consuming-apis-in-angular-displaying-data-in-components.md

Prompted by https://github.com/florimondmanca/www/issues/89#issuecomment-679385037
Use Starlette instead of Bocadillo in example server snippet in https://florimond.dev/blog/articles/2019/02/consuming-apis-in-angular-displaying-data-in-components/

Replace Bocadillo with Starlette

---

server/styles/base.pcss

Blockquotes used to look blank, but not anymore!

Add blockquotes styles

---

scripts/install

**Motivation**
This happens on CI:
```
Using legacy 'setup.py install' for autoflake, since package 'wheel' is not installed.
Using legacy 'setup.py install' for PyYAML, since package 'wheel' is not installed.
Installing collected packages: aiofiles, starlette, watchgod, arel, asgi-sitemaps, gunicorn, MarkupSafe, jinja2, markdown, pygments, PyYAML, six, python-frontmatter, h11, click, uvicorn, pyflakes, autoflake, sniffio, asgi-lifespan, mypy-extensions, regex, appdirs, typing-extensions, toml, typed-ast, pathspec, black, exdown, pycodestyle, mccabe, flake8, attrs, flake8-bugbear, flake8-comprehensions, flake8-pie, httpcore, idna, rfc3986, certifi, httpx, isort, mypy, pluggy, pyparsing, packaging, iniconfig, py, pytest, pytest-asyncio, coverage, pytest-cov, cached-property, …
```

Prevent fallback to legacy 'setup.py install' for wheels

---

requirements.txt

**Motivation**
https://dev.azure.com/florimondmanca/public/_build/results?buildId=860&view=logs&j=10b28c3e-f5e6-5a94-3fa6-e3c41d4e54d6&t=a1527d81-4978-57b2-0bb2-aef732900d3d&l=133
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
httpcore 0.11.1 requires h11<0.10,>=0.8, but you'll have h11 0.11.0 which is incompatible.
```

Install dependencies using pip resolver

---

requirements.txt
scripts/install

Cleanup for #140 
`heroku-buildpack-python` hardcodes the pip version to 20.1.1: https://github.com/heroku/heroku-buildpack-python/blob/main/bin/steps/python#L145
And I haven't found a way to override it.
So in the meantime, let's only apply `--use-feature="2020-resolver"` in `scripts/install`, outside of `requirements.txt`.

Do not use pip resolver on prod

---

.buildpacks
README.md
ci/azure-pipelines.yml
requirements.txt
runtime.txt
scripts/check
scripts/lint

Python 3.9 support is available and:
* CI supports it.
* My `azure-pipelines-templates` now support it.
* Support was added to [Buildpack](https://github.com/heroku/heroku-buildpack-python/blob/v184/CHANGELOG.md#v182-2020-10-06)

Use Python 3.9

---

requirements-dev.txt
requirements.txt
scripts/install

**Description**
* Split `requirements.txt` into `requirements.txt` and `requirements-dev.txt`.
* Also update and simplify `scripts/install`.
**Motivation**
Speed up deploys by skipping installation / compilation of test/dev dependencies.

Split deps between dev and runtime

---

README.md
server/content.py
server/settings.py
server/tools/mdformat.py
tests/conftest.py
tests/drafts/articles/2020/01/test-draft.md
tests/test_app.py

**Motivation**
I can now keep drafts in a git-ignored `debug/drafts` folder, put `EXTRA_CONTENT_DIRS=debug/drafts` in my `.env` file, and have them served along with regular content. Allows me to manage drafts without having to do git branching.

Add support for including extra content directories

---

server/content.py
server/utils.py
tests/test_content.py

Right now crawlers request `/static/img/...`, we need them to request `https://florimond.dev/static/img/...`.
This holds because all images are now hosted on the domain, as per #118.

Use absolute image paths for meta images

---

server/content.py
server/models.py
tests/test_content.py

Not sure exactly when this became functionally obsolete, but it's not used anywhere anymore.

Drop legacy 'home' param

---

.buildpacks
.gitignore
app.json
babel.cfg
locale/base.pot
locale/fr_FR/LC_MESSAGES/messages.po
requirements.txt
scripts/compilemessages
scripts/install
scripts/makemessages
server/content.py
server/i18n/__init__.py
server/i18n/gettext.py
server/i18n/locale.py
server/i18n/middleware.py
server/i18n/routing.py
server/middleware.py
server/routes.py
server/settings.py
setup.cfg
tests/test_i18n.py

Lower-touch alternative to #191 
Add minimal infrastructure for translations.
Essentially adds a `/fr/` page which returns the home page, with the navbar translated in French.
I'd like to start publishing content in French.
This required:
* `locale.py`, `gettext.py`, etc: gettext translations setup, with a `ContextVar` storing the task-current locale.
* `LocaleMiddleware`:  detects any locale in the URL (eg `/fr/...` -> `fr`), sets it for `gettext`, and saves it as `request.scope["locale"]`.
* `LocaleRoute`: a route class that ignores the locale prefix when matching. Usage: `LocaleRoute("/page", ...)` -> will match `/page` (default language), or `/fr/page` (French translation).
This is purely additive. The `/fr/` page is not linked to from anywhere yet (can only be accessed directly). …

Add minimal translations infrastructure

---

server/templates/components/pages/article_meta.jinja

Category link from an article page would be eg `/blog//category/essays` and return 404.
See: https://florimond.dev/blog/articles/2021/04/google-floc/ and click "Essays".

Fix link to category from article page

---

server/content.py
server/i18n/__init__.py
server/i18n/jinja2.py
server/i18n/locale.py
server/models.py
server/resources.py
server/sitemap.py
server/templates/components/pages/post_meta.jinja
server/templates/components/pages/tag_list.jinja
server/views.py
tests/test_app.py
tests/test_content.py
tests/test_i18n.py
tests/test_images.py

Split from #206 
* Migrate category and tag pages to `/en/category/...` and `/en/tag/...`.
* Refactor storage of page data to prepare support for languages other than `en`.

Migrate category and tag pages to /en/ namespace

---

server/content.py
server/i18n/__init__.py
server/i18n/locale.py
server/models.py
server/sitemap.py
server/views.py
tests/drafts/fr/posts/2021/04/test-brouillon.md
tests/test_app.py
tests/test_content.py
tests/test_images.py

Split from #206 
Follow-up to #207 that makes it so that the home page (eg `/en/` or `/fr/`) only shows the list of posts in the current language.
Also update the sitemap generator to include pages from all languages.
So right now https://florimond.dev/fr/ would now be showing "No posts yet" (translating that bit will be done as a follow-up).

Add language support to post list and sitemap

---

server/i18n/routing.py
tests/test_i18n.py
tests/test_legacy_redirect.py

Follow-up to #206 
Link to home page is internationalized, so that eg it shows `https://florimond.dev/fr/` rather than `https://florimond.dev/` when visiting the French version of the site.
Coverage for staying on the same language throughout links should now be complete: home page, categories, links to posts on the home and post detail pages.
This is implemented by enhancing `LocaleRoute`, so that this functionality can be used for future i18n pages as well.
Next up:
* Add a language switch
* Auto-detect language based on request info (I believe browsers send a preferred language).

Internationalize link to home page

---

locale/base.pot
locale/fr_FR/LC_MESSAGES/messages.po
server/templates/views/page.jinja
tests/drafts/en/posts/2020/01/test-draft-prv-1.md
tests/test_app.py
tests/test_content.py

Finalize and add tests for private link support, which was added to `master` via cc52bb8b00dc298f6cfabdb6930108c9ff6d3f7b
These "private links" are useful to share unfinished blog posts, e.g. with external reviewers.

Finalize and test support for private links

---

server/middleware.py
tests/test_ecodesign.py

HTML responses and CSS/JS assets were not [compressed](https://en.wikipedia.org/wiki/HTTP_compression) yet. This PR adds GZip compression.
Comparison of page size / transfer size:
| Page | Size | Transfer size (`master`) | Transfer size (PR) | Transfer size reduction (%) |
|---|---|---|---|---|
| Home | 350 kB | 356 kB | 273 kB | ⬇️ -23.3% |
| Article <br> (_La Garonne à vélo_) | 481 kB | 430 kB | 260 kB  | ⬇️ -39.5% |

Enable GZip compression

---

gulpfile.js
package.json
yarn.lock

CSS output from Tailwind was left as-is. This PR as minification via [clean-css](https://github.com/clean-css/clean-css) and [postcss-clean](https://www.npmjs.com/package/postcss-clean).
CSS size comparison:
| `master` | PR | Reduction |
|---|---|---|
| 24 kB | 12 kB | -50% |

Minify CSS output

---

server/styles/base.pcss
server/styles/components.pcss
server/templates/components/jumbotron.jinja
server/templates/components/navbar.jinja
server/templates/components/pages/post_list_item.jinja
tailwind.config.js

Currently, no `@media print` CSS rules are provided, which meant that printing the page (or generating a PDF) would output HTML in the default (i.e. mobile) style, i.e. with very wide margins and lots of empty spaces.
This PR adds proper `@media print` rules for a print-optimized layout, and makes a few spacing tweaks (jumbotron, lists).
* https://github.com/tailwindlabs/tailwindcss/discussions/1425#discussioncomment-999

Add print stylesheet

---

server/templates/base.jinja
server/templates/components/navbar.jinja
server/templates/components/pages/post.jinja

Follow-up to #251 
Hide the following items, which are not relevant for print:
* Navbar
* Footer
* Comments

Hide more items in print style

---

requirements-dev.txt
requirements.txt
scripts/lint
server/reload.py
server/settings.py
setup.cfg
tests/test_app.py
tests/test_ecodesign.py
tests/test_i18n.py
tests/test_legacy_redirect.py

Batch of dependency bumps
NOTE: `exdown` is marked as deprecated. It turned to extracting code-blocks for pytest usage, rather than further manipulation like we do. Might need to revive #254...

Bump dependencies

---

ci/azure-pipelines.yml

`Build` job was not specifying an Ubuntu version, so it was using Ubuntu 16 which is not supported by AZP anymore. AZP wants us to specify a version explicitly, here using `ubuntu-latest` as in other AZP templates.

Update CI "Build" job and templates version

---

Makefile
Procfile
server/__init__.py
server/app.py
server/main.py
tests/conftest.py

It's very easy to end up with circular imports because of the import of `app` in `server/__init__.py`.
This PR moves that to a separate module, that's specifically imported by uvicorn/gunicorn.

Refactor: use a main module

---

server/domain/repositories.py
server/web/middleware.py
tests/conftest.py
tests/test_app.py
tests/test_legacy_redirect.py
tests/utils.py

* Drop `typing.*` usage that can now be built-in annotations, eg. `list[str]`
* Switch from `import typing; typing.X` to `from typing import X`

Update type hints

---

server/domain/entities.py
server/infrastructure/adapters/frontmatter.py
server/infrastructure/html.py
server/infrastructure/pages.py
server/infrastructure/repositories.py
server/web/templates/components/meta.jinja
server/web/templates/components/navbar.jinja
server/web/templates/components/pages/post.jinja
server/web/templates/components/pages/post_list_item.jinja
server/web/templates/components/pages/post_meta.jinja
server/web/templates/views/page.jinja
server/web/templating.py
tests/test_app.py
tests/test_content.py
tests/test_images.py

Follow-up to #340 
Metadata coming from a Markdown YAML frontmatter is an implementation detail. The `Frontmatter` entity was really a `Metadata` entity. HTML `<meta>` tag rendering has been moved to an `infrastructure/html.py` module.

Turn Frontmatter entity into Metadata entity

---

ansible/roles/www/tasks/main.yml

I received reminder emails from LetsEncrypt, which indicates enabling the `dokku_letsencrypt` plugin is not enough, and [Automatic certificate renewal](https://github.com/dokku/dokku-letsencrypt#automatic-certificate-renewal) has to be enabled.

Ensure Letsencrypt cron job is setup

---

server/domain/repositories.py
server/infrastructure/repositories.py

Post-merge fix for #359 
Category pages such as https://florimond.dev/en/category/tutorials/ were not showing any pages anymore.
Aka the problems of no type checking in Jinja2 templates.
Also of not having any E2E tests.

Fix list of category posts

---

ansible/roles/www/tasks/nginx.yml

Let's Encrypt certs were not getting renewed which made the site unavailable after a while
Cron job surely needed to be installed for user `root` (defaulted to current user, aka `debian`?)
Also avoid special_time just in case, use "At 3am on Mondays"

Fix certbot renewal cron

---

server/web/templates/components/jumbotron.jinja
server/web/templates/views/post/detail.jinja
tests/test_indieweb.py
tests/utils.py

* Refs #160 
This PR adds [`h-card`](https://microformats.org/wiki/h-card) to home page and [`h-entry`](https://microformats.org/wiki/h-entry) to blog posts as per step 1 or Level 2 of https://indiewebify.me/

Add h-card and h-entry microformats
